using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Day4
    {
        //        public static void Main(string[] args)
        //        {
        //            string[][] input = {new string[] { "nyot", "babgr", "babgr", "kqtu", "kqtu", "kzshonp", "ylyk", "psqk" },
        //new string[] { "iix", "ewj", "rojvbkk", "phrij", "iix", "zuajnk", "tadv", "givslju", "ewj", "bda" },
        //new string[] { "isjur", "jppvano", "vctnpjp", "ngwzdq", "pxqfrk", "mnxxes", "zqwgnd", "giqh" },
        //new string[] { "ojufqke", "gpd", "olzirc", "jfao", "cjfh", "rcivvw", "pqqpudp" },
        //new string[] { "ilgomox", "extiffg", "ylbd", "nqxhk", "lsi", "isl", "nrho", "yom" },
        //new string[] { "feauv", "scstmie", "qgbod", "enpltx", "jrhlxet", "qps", "lejrtxh" },
        //new string[] { "wlrxtdo", "tlwdxor", "ezg", "ztp", "uze", "xtmw", "neuga", "aojrixu", "zpt" },
        //new string[] { "wchrl", "pzibt", "nvcae", "wceb" },
        //new string[] { "rdwytj", "kxuyet", "bqnzlv", "nyntjan", "dyrpsn", "zhi", "kbxlj", "ivo" },
        //new string[] { "dab", "mwiz", "bapjpz", "jbzppa" },
        //new string[] { "hbcudl", "tsfvtc", "zlqgpuk", "xoxbuh", "whmo", "atsxt", "pzkivuo", "wsa", "gjoevr", "hbcudl" },
        //new string[] { "gxhqamx", "dradmqo", "gxhqamx", "gxhqamx" },
        //new string[] { "yvwykx", "uhto", "ten", "wkvxyy", "wdbw" },
        //new string[] { "kzc", "ndzatgb", "rlxrk", "hfgorm", "qwgdky", "ndzatgb", "rhvyene", "qaa", "wxibe", "qwmku", "nmxkjqo" },
        //new string[] { "qwx", "ubca", "dxudny", "oxagv", "wqrv", "lhzsl", "qmsgv", "dxs", "awbquc", "akelgma" },
        //new string[] { "rrdlfpk", "ohoszz", "qiznasf", "awchv", "qnvse" },
        //new string[] { "ggsyj", "czcrdn", "oolj", "sibjzp", "ibzjps", "asp" },
        //new string[] { "vbcs", "ypgzae", "xcvpsr", "ptvb", "leoxqlq", "zmpt", "fhawu", "yfi", "tvbp" },
        //new string[] { "ejkr", "qlmag", "nsz", "jwpurli", "nhsml", "asksnug", "mes" },
        //new string[] { "kkgkjml", "kklmgjk", "kjgpx", "iquytbj", "eccceb", "mfv", "iuyqjbt", "ovv" },
        //new string[] { "uoklkco", "zzey", "sdfhiyv", "ytdeg" },
        //new string[] { "azr", "mjv", "raz", "arz", "rdfb" },
        //new string[] { "pir", "dafgsah", "dafgsah", "kndjbml", "estcz", "yjeoijp", "kkcws", "ebq", "puwno" },
        //new string[] { "iqymwc", "tac", "vlqc", "bmnkz", "xustm", "leqi" },
        //new string[] { "gwdjed", "cfha", "axz", "xjuq" },
        //new string[] { "abfjsg", "pahat", "qlj", "zan", "qsfn", "iozfys", "jnvu", "bis", "jakggq" },
        //new string[] { "afwuejn", "zrbu", "zurb", "hrn", "lwvjb", "jnwixla", "aufejnw" },
        //new string[] { "vkqn", "cuzf", "humhriz", "webnf", "uzfc", "zfuc" },
        //new string[] { "eznxd", "kgbfy", "jqyc", "net", "vzfege", "tprzyc" },
        //new string[] { "mqnapzn", "vrgw", "ilzp", "vgw" },
        //new string[] { "aie", "zkkih", "fhpwu", "bbn", "fhpwu", "wvxxgmd" },
        //new string[] { "ksoasrn", "yll", "mvdjxdo", "wydymx", "dmodvjx", "drnjlm", "tcjpjhj", "xzakb", "wrsbuwl", "vaygdwf", "rsasonk" },
        //new string[] { "qahbh", "tfhkl", "apdqqpm", "tfhkl", "nsox" },
        //new string[] { "xkelwve", "mvdmesj", "xrto", "tgku", "gkb", "bpe" },
        //new string[] { "nni", "nyylpu", "cyusxe", "zydeyok", "yokzdye", "xiscesy" },
        //new string[] { "itwsfr", "eqwrx", "igqkvif", "whklwdb" },
        //new string[] { "lpa", "hwci", "suwqfln", "xis", "sfht", "lzek", "ajecd" },
        //new string[] { "svpf", "eulute", "eya", "gvmsd", "app", "claria", "tjtk", "zjt", "agdyemi", "bixewo" },
        //new string[] { "gmzglxi", "zlgouy", "bejg", "kte", "xlf", "giquj", "mjeq", "ivjkw", "ktbhaga", "hoffyrt" },
        //new string[] { "wwjy", "dtf", "ftd", "agei", "yde", "xhbfo", "fyridy" },
        //new string[] { "gexcy", "hetkz", "ufflrfi", "frifluf", "plb", "kqre", "etxo", "elg", "henqy", "fspm" },
        //new string[] { "khaemn", "buec", "ichau", "wxctsxg" },
        //new string[] { "cgmv", "ujyvcuu", "jta", "yux", "ccx", "skrafkn", "cmyc", "yidqhv", "ltb", "ycnajry", "zitq" },
        //new string[] { "ybsahqn", "pio", "veeze", "vdztjz", "iedou", "pio", "sue", "ijbz", "gvqncl", "vpa", "ijbz" },
        //new string[] { "hkfi", "xzrsyke", "hikf", "mxolx", "xlxmo", "ungfc", "tst", "xjzd" },
        //new string[] { "tpx", "ioprco", "qixlv", "ipocro" },
        //new string[] { "oahmwrv", "homvraw", "vws", "ntmbdvx" },
        //new string[] { "fxlg", "wnuz", "ogt", "bxgtul", "vmfh", "nwuz", "glfx", "tgxdq", "bxfv", "kajuh" },
        //new string[] { "vrhqn", "nrqvh", "tgogb", "vya", "ragbro", "ulrz", "uava", "kexoi", "yav", "vkfe" },
        //new string[] { "bxxy", "tyxgxd", "oabsud", "bauosd", "jlch", "bdmrqq", "wqhjwb", "ayblb", "hclj" },
        //new string[] { "sfzsgsc", "sfzsgsc", "jbrvh", "sfzsgsc", "bdhy" },
        //new string[] { "wixleal", "vhnqbfw", "qwfnhbv", "woco", "oowc" },
        //new string[] { "exkkwz", "wekxzk", "krxbua", "nshxqgh" },
        //new string[] { "gkn", "blxgui", "nkg", "gnk" },
        //new string[] { "otsa", "isqn", "otsa", "isqn" },
        //new string[] { "ude", "xedl", "ude", "xedl", "amkktp" },
        //new string[] { "teroe", "yuvbd", "inf", "mpytuvz", "xiq", "xqi", "ovqetn" },
        //new string[] { "zyq", "ybeifwx", "fvoqp", "vhoduy", "bcq", "wbxl" },
        //new string[] { "zymiid", "vafcqv", "vjbmekf", "lgxkma", "bjti", "qfavcv", "iqp", "fnbu", "lakmgx" },
        //new string[] { "rkaqvd", "vylkh", "jfdxh", "imxxg", "bbrt", "imxxg", "rkaqvd" },
        //new string[] { "yajg", "qnhhs", "bzmb", "eyk", "hijcg", "tkij", "iwr", "jvwp", "dipzd", "jvwp" },
        //new string[] { "btzhw", "zttheyo", "ravsbz", "bmbba", "majoe", "ykrs", "tbxqf", "tai", "cgsvpu", "srbavz" },
        //new string[] { "vsyczfs", "ymg", "vsyczfs", "wxlwaqb", "oouio", "owek", "wxlwaqb", "azvbqiq" },
        //new string[] { "ghrapd", "ghrapd", "wisq", "wisq" },
        //new string[] { "znmleu", "aztnkbs", "wxc", "gycxd", "vqenhh", "geqyo", "rpjg" },
        //new string[] { "kxbom", "gzz", "zzg", "zgz" },
        //new string[] { "dfsesc", "okwb", "dfsesc", "okwb" },
        //new string[] { "egpwqbe", "djlk", "xpkxa", "hoo", "eepbqwg" },
        //new string[] { "nxdfror", "yfhkhn", "zgea", "fkspva", "rjgg", "bnmq", "ddsf", "rjgg", "gkinm" },
        //new string[] { "vdrxfom", "wbdwu", "dhkt", "xtvzc", "zjobo", "aqvgrt" },
        //new string[] { "svddsgz", "mhcrbcp", "wmpd", "mhcrbcp", "klim", "ddlnxv", "wrdftrc", "ddow", "wrdftrc" },
        //new string[] { "obxr", "wscs", "new", "brxo", "wen", "epns", "cvjvxts", "ilnc" },
        //new string[] { "rwezl", "vmbut", "kgblt", "xfg", "vnhlebq", "nzqdzxm", "ynh", "wokrezy", "zub", "nzzqxdm" },
        //new string[] { "vephajp", "bzupele", "mltzglh", "sbgn", "vephajp", "lhve", "mltzglh" },
        //new string[] { "slajp", "kyaf", "vlnvy", "srfietn", "ayfk", "inaufex", "fanuexi" },
        //new string[] { "vazwg", "kjg", "qanzso", "ptuu", "vvlwq", "uupt", "kohhql", "jkg" },
        //new string[] { "xmmmpky", "rbqimi", "slvxsf", "tlcwm", "pbf", "pks", "iucx", "rbmiqi" },
        //new string[] { "irkup", "jvu", "tkeioz", "avdu", "suxamf" },
        //new string[] { "tmgih", "ldca", "jswka", "dblzzt", "rap", "rgqyy", "gyrqsk", "nnnn", "pok" },
        //new string[] { "pdbjhrl", "gsvxbqr", "nqfkhtc", "ngn", "okbgzd", "pdbjhrl", "oostjtm", "okbgzd" },
        //new string[] { "mzqfdat", "dujh", "aeplzqh", "acbguic", "vlzdt", "amyszu", "amyszu", "jqecky", "bhl", "hjqnimq", "xoy" },
        //new string[] { "dszafr", "bqampg", "epozj", "sfrlpe", "dszafr", "wfurku", "sotjpg", "wagtnxy" },
        //new string[] { "jbmo", "jbmo", "plbfkvw", "bkc", "jbmo" },
        //new string[] { "ehelldu", "vrid", "unnf", "vrid", "xqiu", "tbibjyi", "bmbpsmq", "tpqyefx", "xqiu" },
        //new string[] { "rpgm", "zzbj", "cjgfdyb", "bdjfgcy", "rzqecd", "miyvfbu", "aqlkagf", "hsuxwgl" },
        //new string[] { "gvywzp", "phvnd", "ypwypbm", "yfelxx", "egbr", "lcfyz", "hecdhkj", "xxfley" },
        //new string[] { "tsmebin", "tbsnmie", "mkijj", "ijjmk" },
        //new string[] { "cghxrqs", "vzxle", "wrfghv", "skighgt", "zviteab", "plcrgv" },
        //new string[] { "ezdirp", "rxkw", "horcek", "qcgny", "inx", "nikb", "tigzp" },
        //new string[] { "eidk", "sactjci", "sre", "vkapava", "owvf", "eyds", "eyds" },
        //new string[] { "vvjdm", "uye", "tjixj", "azklizl", "pnb" },
        //new string[] { "tcrimv", "xye", "twii", "xye", "twii", "tad" },
        //new string[] { "mtxcg", "lwjxdj", "zjudqu", "ekoujd", "ysf", "ajtfta", "dkj", "lwjxdj" },
        //new string[] { "aowhmvv", "kkic", "kjize", "fnohl", "ukx", "remfmii", "usbp" },
        //new string[] { "wkossu", "limxmhp", "xnoeocb", "wkossu", "lnrlqf", "kjozfg", "xeulstx", "sjncsw", "ekaimuv", "xnoeocb", "sxjegcg" },
        //new string[] { "lsfe", "zpewzlc", "yhjyiay", "lou", "ukhi", "lpwezzc", "slef", "zvtidgg", "kdeseq", "enka", "tfvgudr" },
        //new string[] { "ovfsa", "vuv", "tbtorv", "tbtorv", "gmxn", "opspw", "lli", "mfzvkv", "zlyhr", "oznalr" },
        //new string[] { "kugrpw", "sduq", "rdc", "ciaxwir", "ylnzwec", "kugrpw", "sduq" },
        //new string[] { "obevuau", "thu", "jpyfvof", "rpawwo", "obevuau", "gsvoutr", "quiaei" },
        //new string[] { "xpgua", "pbxa", "pxgau", "kdan" },
        //new string[] { "ohyzqk", "abxgg", "xozgai", "nib", "axozig", "bni", "fucgykm", "jpkswt" },
        //new string[] { "jrgu", "dmozts", "jrug", "ufpho" },
        //new string[] { "qojzue", "uzeojq", "txuhj", "eqjzou" },
        //new string[] { "wcvj", "qwlravl", "niyxf", "oiaptlk", "wlxnnzj", "jgdzap", "jgdzap", "lfgn", "bdt", "sfga", "adrypo" },
        //new string[] { "ylah", "eedu", "rvwdpmq", "eedu", "ylah" },
        //new string[] { "quages", "kmla", "yjqua", "dzxcfam", "srjag", "wujmcv", "qujya", "ssaol", "uzdwi" },
        //new string[] { "gdsppz", "yqxlish", "yfkjbbf", "ecnzu", "ejvtv", "cdjwre" },
        //new string[] { "slsls", "pcmrq", "zax", "btrc", "kliv", "ntho", "gymkk", "kkq", "pcrmq", "mvnw", "sjfegpx" },
        //new string[] { "ryz", "jfw", "eki", "wvibww", "qdzylg", "whbagp", "ffrfjg", "wdhnqpm", "hcrz" },
        //new string[] { "tcjqfh", "tmvzp", "mpztv", "vpmzt" },
        //new string[] { "xood", "xutgof", "teqov", "fqyyub", "oakm", "rzaheiq" },
        //new string[] { "axagoq", "jawbz", "sexucp", "sexucp", "atenr", "edekcwn", "edekcwn", "agl", "ecj", "gbje", "gipivfq" },
        //new string[] { "poqv", "qopv", "bos", "flhghs", "gshlfh" },
        //new string[] { "rxd", "dzphnb", "bwmna", "vxd", "rxd", "sbk", "kuor" },
        //new string[] { "kqeelq", "jqbyh", "xczqzqe", "jbkmx", "kelqeq", "xqcfqn" },
        //new string[] { "jdfy", "qzjyz", "xvqyo", "jdfy", "xvqyo" },
        //new string[] { "vyoqyd", "pwayqag", "eygmdt", "smakwc", "veftikz", "fzeikvt" },
        //new string[] { "aozgkne", "mpd", "mktgoew", "eepp", "zlwycr", "eepp", "hswbxcx", "nmi", "ddnfr", "eepp" },
        //new string[] { "dgpfp", "cfhhqdx", "vjrb", "uyimbm", "byx", "hfdhxqc" },
        //new string[] { "fxq", "jcouwfy", "uhuao", "zsab", "xjao" },
        //new string[] { "noudveu", "egxyuqw", "hmnnv", "vovt", "wmqkx", "syatiac", "whkd" },
        //new string[] { "gxyzk", "opgb", "kjxp", "delavq", "hsnvk", "kfn", "irkcfq", "lvc", "aadcwy", "opgb" },
        //new string[] { "exuiupk", "ddiiyvm", "nsggpj", "ddiiyvm", "nsggpj" },
        //new string[] { "hhjby", "rfejzp", "akxzs", "nconlt", "rynivtq", "voloj", "qwhhll", "ubvx", "yxuacz", "miuwxh", "ppe" },
        //new string[] { "uspqvx", "supvxq", "cekv", "niddfuw" },
        //new string[] { "optzcag", "sra", "ajs", "ozacptg", "yxkludq", "jjpvldz", "mxo", "mox" },
        //new string[] { "dko", "qyec", "iuxbrbj", "dlz", "jxribub" },
        //new string[] { "ywlyz", "vipfh", "amsfr", "fwiozi", "tahjov", "tap", "rsea", "zwlyy", "oqdyfbo" },
        //new string[] { "xeqml", "jwy", "eguc", "bvzvh" },
        //new string[] { "crp", "mxsihvo", "wwtg", "gsypx", "mxsihvo", "qpfw", "looca", "gewvy", "zjqki", "tdkuxo", "crp" },
        //new string[] { "mqlnzm", "yihsvrl", "hhtwcv", "kigymqu", "yswki", "hksk", "vbiujq", "xeqz", "irzcq", "cpnz" },
        //new string[] { "zxhfsw", "uuyhwid", "nzabem", "mmfk", "wszfhx", "shxzwf", "hqnrvsq" },
        //new string[] { "hfjajdl", "qwmk", "hjdalfj", "mwkq", "gqbku", "dsszk" },
        //new string[] { "fbiy", "pujq", "htgaqqq", "yro", "ztpe", "yiufb", "fnpi", "ggchdgz" },
        //new string[] { "sixq", "jsboan", "eoie", "msdrwzw", "sixq", "njsrc", "sixq", "yimqoi" },
        //new string[] { "pbxgv", "kqmi", "hjuk", "bbtrlta", "bqwm", "bgehofj", "ainqhm", "qoypsil", "manhiq", "ogebhfj", "lvmuo" },
        //new string[] { "wnax", "aen", "fthpcke", "tcz", "yadjmva", "mydavaj", "rcfkc", "krfcc" },
        //new string[] { "lkatiw", "zxliii", "usdj", "oopxl", "yylv", "bkjfy", "gtlyjv", "usdj", "muqazdb" },
        //new string[] { "yqonaxv", "wqnvoo", "hfpll", "oyxnlfs", "fgajc", "khhtzr", "hfpll", "gsvvipz", "wbjxsnp", "dcdikt", "hqw" },
        //new string[] { "vvuv", "kspmnz", "zvmryqd", "egvuz", "eazkhz", "kspmnz" },
        //new string[] { "xgq", "dziwiym", "gsl", "nbzmsta", "ccbzn", "yalof", "dbbugq", "aar", "ywmbvk", "yofla", "dcwb" },
        //new string[] { "qrtyhhw", "xeyo", "vlym", "ulzzbl", "hrxyb", "qeyu", "jqdkewk", "oxye", "evaxz", "kybc", "bssyt" },
        //new string[] { "eqrf", "cfyy", "kwhohw", "ozg", "jsc", "egz", "jsc" },
        //new string[] { "vct", "cet", "ixxvmz", "ibhvndq", "eks", "dpi", "jzfwdqv", "saeh", "jqzdfwv", "vwfdqjz" },
        //new string[] { "vus", "vus", "kitvvgq", "wpi", "alfncf", "gzj", "oxcy", "fith", "oxcy", "ecbsr" },
        //new string[] { "uacculk", "guwhwdp", "cankcv", "yswy", "bmby", "sve", "dvonm", "nran" },
        //new string[] { "ydftm", "wszgaex", "rgbw", "otd", "dbet", "lhsxndd", "jqfyx" },
        //new string[] { "vhawg", "hwagv", "uagy", "fveik", "nrsew", "zujw", "hawvg", "dzfmt", "agzgw" },
        //new string[] { "uqdj", "talb", "uqdj", "aizyuqm" },
        //new string[] { "pbbejee", "szdtohv", "tycfow", "xwne", "qzlqy", "dxcwejz", "pqdqrc", "wfyotc", "gdqt", "uxaeug", "wtldm" },
        //new string[] { "hmzmd", "oyp", "pyo", "opy" },
        //new string[] { "qwdh", "kwpll", "kwpll", "zsbez", "uxg", "klr", "uxg" },
        //new string[] { "myqr", "zza", "kqpcos", "adsql", "eumunrv", "qlaeumx" },
        //new string[] { "acyye", "xvdewe", "nwkhuz", "bzcmx", "asw", "ostiwk", "mfzu", "nwkhuz" },
        //new string[] { "memq", "uqadd", "kfj", "dses", "lrxb", "hxygp", "dsse", "bxbr", "hgpxy", "uavrar" },
        //new string[] { "mjmk", "lsdttuz", "qjkg", "yfthmkn", "pram" },
        //new string[] { "pctfq", "aly", "usim", "shihap", "uims", "xkfgp", "ksrbn", "ifvsyl" },
        //new string[] { "cdma", "nnnu", "hdm", "dhm" },
        //new string[] { "kpt", "upgsm", "ohvrrqf", "qwps", "wjcbve", "ohvrrqf" },
        //new string[] { "wowphgb", "nteme", "otizypb", "eumgvb", "puoctli", "opicult", "wbohwpg" },
        //new string[] { "fppz", "ftkql", "sbut", "lkqtf", "svif", "viqhlnn", "buts", "lljhbd" },
        //new string[] { "oqk", "uinby", "rqy", "vbjhf", "oul", "hzfo", "coca", "glpy", "brjy", "yglp", "qnvhvei" },
        //new string[] { "sbbwr", "dnyrux", "gpikv", "nsx", "aawyeq", "uhtucwq", "rhxzy", "jgx", "bdgdrl", "dnyrux", "lgfgi" },
        //new string[] { "agn", "mljz", "hgmglem", "popu", "jtapub", "agn" },
        //new string[] { "ehfpgr", "bnobvg", "bnobvg", "bnobvg" },
        //new string[] { "ozgzedn", "godezzn", "art", "atr" },
        //new string[] { "urz", "rzu", "xzyc", "rjhwi", "kgiodi", "doiigk", "layr", "dwbxu" },
        //new string[] { "rkcbav", "pnp", "bpsmm", "ifivfe", "csouqpw", "fyswzbd", "csouqpw", "bnjt", "rnnoxed" },
        //new string[] { "hpjgtcc", "ctcpgjh", "cchjtgp", "lxn" },
        //new string[] { "cinokbx", "uyaz", "uyaz", "uyaz" },
        //new string[] { "bphfwad", "bphfwad", "bphfwad", "yml", "izlhlb", "dvjvo", "jeropar" },
        //new string[] { "ocgftcl", "wshjk", "zbinw", "fcotlgc", "xdj", "nwibz" },
        //new string[] { "zbze", "hllno", "rmq", "invd", "gupoxr", "gwumc", "vnzj", "fcvvhjo", "dnn", "sfsxw" },
        //new string[] { "oqlhkz", "hgf", "yxiahks", "vhzvl", "ayshkxi", "irmwkmq" },
        //new string[] { "apeqic", "ahwu", "abxjrd", "tuwrd", "pynnil", "eohmlgo", "lafx", "ybpofe", "wbznxv", "swuafas" },
        //new string[] { "cpg", "jpsfo", "jposf", "rer", "ixeydpz" },
        //new string[] { "rhqrwvn", "wrhqnrv", "xptms", "jhc", "rnqvhwr" },
        //new string[] { "zfpl", "tukxzda", "lifkqtd", "ynfuno", "cttx", "ctxt", "tlqdkfi", "ueswv", "wbipfbe" },
        //new string[] { "eblw", "bwbjg", "fuu", "qqm", "qtv", "qtv", "isbl", "denfcb" },
        //new string[] { "ick", "yqwcffk", "pvcchd", "apkjyc", "ouu", "uyfe", "nplid", "ick", "caqscs", "sddkx" },
        //new string[] { "rtzh", "idn", "snnw", "xmlou", "idn", "kdhenl", "rtzh", "ujwttl", "pkynkhe" },
        //new string[] { "dnwha", "fpv", "dnwha", "iqi", "xggepo", "dnwha" },
        //new string[] { "yjvk", "saay", "enxqhw", "wigoah", "dzasyr", "nnt", "artl", "iqwia", "jpp", "xmfr", "hwigao" },
        //new string[] { "ryt", "heenuai", "ytr", "gqew", "hyb", "byh", "wdurx", "kmd", "adgjz" },
        //new string[] { "ypdqeji", "sfkkfhn", "stms", "cdmyh", "nqllx", "utiphia", "gxbx", "zflhtgo", "yurztx", "eni" },
        //new string[] { "pwlhlt", "lhlwpt", "rfkvlgr", "tucajej", "ckujc", "ntcyae", "xestygt", "eshmggk" },
        //new string[] { "gtfb", "codwc", "vjtli", "ffmjwx", "ruoekt", "cylrm", "ktroue", "dfaxzvs", "kkgejzi", "ewucgu", "jyatrum" },
        //new string[] { "ersbag", "cod", "xssha", "aqzbe", "kxu", "bzghhqk", "pbs", "bizvqk", "bhbbd", "bps" },
        //new string[] { "vhci", "ypxf", "bxzor", "unngl", "xilpzpk", "civh", "nykora", "vchi" },
        //new string[] { "cyb", "cceu", "negnld", "nbcfs", "pxsjgh", "xah", "nbcfs", "nbcfs", "jabpxg", "wtanv", "qhztvr" },
        //new string[] { "cljgzkn", "lrdeina", "hrjoz", "kdgpn", "vqkmpal", "nivk", "scvnu", "vzuausp" },
        //new string[] { "nif", "fin", "uxjbip", "xxztsn", "yyo", "opueh", "zxs", "qnso", "paedey", "hsd", "fttvqdn" },
        //new string[] { "gbnkmpr", "afo", "aof", "ryyudy", "gbmpnrk" },
        //new string[] { "uaa", "npb", "dkit", "npb", "buadan", "esv", "npb", "hwrj" },
        //new string[] { "hws", "dfgq", "fcyty", "qszhu", "chyxxl", "ytmpb", "azxl", "jrsn", "boqrx" },
        //new string[] { "hkzlnkd", "fkilvog", "xbubu", "fbgbp" },
        //new string[] { "fgi", "inmay", "uliytc", "vgkcw", "qsoe", "uliytc", "isjhix", "oyir", "ocaq" },
        //new string[] { "qrzkpm", "dpzetbr", "zommsxo", "cixg", "nwjyvp", "bet", "wyjpvn", "cgxi", "tsncd" },
        //new string[] { "uvlf", "lufv", "ulfv", "cigl" },
        //new string[] { "uwwf", "thr", "kdq", "fhjmty", "bvxue", "vcwwmk", "kdq", "nzajq", "bxkf" },
        //new string[] { "qcwduju", "idxaja", "qcwduju", "idxaja" },
        //new string[] { "fnarz", "pstzfne", "nco", "qzf", "kcevoo", "qwx", "csvsxga", "pstzfne" },
        //new string[] { "twug", "xrwy", "uoctfl", "bkh", "yxrw" },
        //new string[] { "unpdnbe", "apf", "cvm", "bpullu", "fyels", "tjpri", "jyw", "unpdnbe", "xfyekay", "vhk", "zpyb" },
        //new string[] { "rbv", "psirdv", "psirdv", "mnjrp", "qpwc", "vicismd", "qpwc" },
        //new string[] { "zjj", "zjj", "kesyhow", "eqcfqy", "vqy" },
        //new string[] { "zazpd", "gmea", "aobl", "dcs", "mage", "hqjdpwc", "bvxr", "srw" },
        //new string[] { "rhcdb", "nzsa", "jgcgc", "rhcdb", "wxs", "vsvvptn", "zvckqo", "wxs" },
        //new string[] { "unyet", "prchn", "fiwter", "wvgknes", "dvzbxfs", "ufet", "neuyt", "fczlrx", "bpocdci", "vdsfzbx" },
        //new string[] { "znfev", "fwrdarx", "knqkv", "ojiv", "ojiv", "fwrdarx" },
        //new string[] { "tbtlo", "hdashg", "kyspxm", "ypmkxs", "nmrk" },
        //new string[] { "fzr", "zqxaszt", "frz", "xzrre" },
        //new string[] { "shueb", "iraetk", "uhsv", "duvah", "uhsv", "zstysc", "nrfllbc", "emrknka" },
        //new string[] { "vzkrmp", "mgtkjnw", "njr", "bwjgp", "jdwyyhv", "yudha", "wbvmx", "ewu", "urhiioq" },
        //new string[] { "yjq", "xxr", "swvm", "aipdj", "apjid", "tfsq", "gfqg", "izrvhev" },
        //new string[] { "iljuqt", "fpo", "fxadit", "iljuqt", "iljuqt" },
        //new string[] { "zrj", "poewso", "vsje", "bsprbmc", "vsje", "yfwf", "ybu", "dmkqib", "ybu", "hlrpdi", "ymh" },
        //new string[] { "apxaeq", "bgdm", "mqty", "whyay", "mnuzfgk", "awm", "bgdm", "mwwi", "ekw", "bgdm" },
        //new string[] { "dpdbfkm", "crrg", "mkph", "kphm", "grcr", "ukbk" },
        //new string[] { "ilqm", "wroz", "mqil", "qlim" },
        //new string[] { "pnlx", "nwadw", "uabelu", "rueamxr", "wjer", "uwge", "jwer", "ywagrx" },
        //new string[] { "akuil", "nkh", "oitq", "werli", "werli" },
        //new string[] { "fkmhcr", "ieoj", "xfsa", "xfacoeb", "tcg", "poomcme", "vck", "zmpc", "djcqgkf", "kft" },
        //new string[] { "csyk", "qni", "hqfrye", "zyyxz", "ggynzad", "pjpokmu", "bigqa", "qie" },
        //new string[] { "lkpenw", "zyllii", "qtbvdq", "zqnu", "ichftg", "xazped", "agl", "irhlbiy", "snlwfe", "twliar" },
        //new string[] { "acsrba", "dzz", "ivylbl", "rfcdd", "rfcdd", "qcg" },
        //new string[] { "zbui", "fomvpx", "zjhmgl", "sivtffu", "xuhswzt", "fzeid", "tgj", "mzok", "mozk", "afbhuje", "tzswxuh" },
        //new string[] { "nupjiat", "fdxkbn", "tuatp", "jhdfnub", "yitdk", "yghqw", "nupjiat", "ibi", "edfv", "tuixw", "auwjm" },
        //new string[] { "focht", "mnprh", "tljj", "ayp" },
        //new string[] { "pjdnl", "uaoworh", "iqm", "gic", "dqlu", "spn", "heuymio" },
        //new string[] { "kvg", "ferrvhp", "unvzsd", "qdcpd", "rji", "zpch" },
        //new string[] { "nhvay", "chuzg", "pyhdd", "hnmrnq", "zeidhf", "pyhdd", "ohy", "hnmrnq" },
        //new string[] { "boa", "sau", "gxh", "grx" },
        //new string[] { "gwo", "utwpd", "zcsrx", "gow", "bnm" },
        //new string[] { "xoqniyd", "hmithl", "xoqniyd", "hmithl" },
        //new string[] { "yqqsbzo", "stca", "zcsjnqf", "skbueeu", "tlbkef", "mvqbg", "igzr", "wujuz", "yqqsbzo", "kkfe" },
        //new string[] { "wgzuepu", "wge", "fkrxuag", "csenx", "tkngoz", "wge", "azueyxs" },
        //new string[] { "get", "xiryxs", "xiryxs", "xiryxs" },
        //new string[] { "wammvx", "edy", "hahetl", "xmvawm", "dye" },
        //new string[] { "lscxxgi", "anmax", "quo", "cqprwn", "imocarq", "gnbfhe", "rcnqpw" },
        //new string[] { "znpmid", "yaluvzn", "ydm", "ckh", "uhso", "rrk", "wbby", "lwxsu" },
        //new string[] { "atppk", "byf", "dzz", "uift", "nqejgm", "njgeqm" },
        //new string[] { "dtqmy", "iog", "ahub", "habu" },
        //new string[] { "hkthdwt", "pfxlwsu", "hkthdwt", "hkthdwt" },
        //new string[] { "tsuiue", "tsuiue", "yais", "tsuiue" },
        //new string[] { "swooqmp", "rqrcs", "ngr", "vujrq", "inuu", "rqrcs" },
        //new string[] { "dhu", "zxdfiyv", "xuz", "xuz", "mgaty", "mgaty" },
        //new string[] { "kiiiz", "zco", "qdv", "vfgkj", "rders", "zco" },
        //new string[] { "trszp", "havbm", "redpeqk", "gktp", "ifvzvwl", "yfoxnm", "tzg", "avzd", "otiouso", "eks", "lqlutwb" },
        //new string[] { "cfiru", "lpdy", "kpeas", "mdc", "lxnjjqz", "nqyyb", "xkjsug", "rcifu", "dln" },
        //new string[] { "jga", "ijgkjo", "qhbnupb", "ofzqn", "iokjjg", "gaj", "lrh", "pkynrcr", "jgatk" },
        //new string[] { "bexwc", "tat", "tat", "otsngaa" },
        //new string[] { "feh", "mjxbs", "ehf", "cyfhlv", "vvdgdu", "hef" },
        //new string[] { "njlvq", "ojwaes", "awsejo", "ktyvxd", "qeyeze", "bpoaj", "ulgngn", "zyeqee", "kqc", "bsdzzvq" },
        //new string[] { "hbfp", "vnhs", "vnhs", "pko", "pxnxgm" },
        //new string[] { "bmy", "bzpn", "bzpn", "bcfep" },
        //new string[] { "cju", "nqjy", "yjqn", "bbrj", "esgzw", "swgl", "bjrb" },
        //new string[] { "cxvrshm", "rbglkyv", "kqwzcyd", "azqr", "ckwbbew", "fhgqv", "nfk", "lactzh", "ssqpwbr", "wbewbck" },
        //new string[] { "ptcb", "gqkb", "apcc", "okl", "jbbgk", "qni", "bqu", "slydyo", "qhh", "dqd", "osv" },
        //new string[] { "zbisefn", "bmxcljk", "bmxcljk", "arkamus", "vpq", "uxuwvb" },
        //new string[] { "ksik", "xbzk", "lahh", "ctfur", "sxh", "rduokr", "xqou", "zwbgqsp", "skik" },
        //new string[] { "hwhmfk", "hwhmfk", "bjpxzg", "qqftmu", "ijyv", "igvayf", "bjpxzg" },
        //new string[] { "askxqew", "tibx", "pqaczy", "fhzyec", "echzfy", "cezfhy" },
        //new string[] { "omzyy", "mbzfvsn", "kkoff", "qgqn", "crnnkn", "krx", "oqp", "jhn", "anb", "qte", "qxt" },
        //new string[] { "jypnwn", "vjbnbsl", "axf", "pldxbq", "pdoy", "rmxcvig", "cpad", "yhah", "rzqewkg", "nmzkkr", "erjo" },
        //new string[] { "visidzp", "bujlfn", "xuomjj", "mjnqn", "wgflg", "skb" },
        //new string[] { "oer", "oer", "lfi", "zyqnem", "lfi", "guljz" },
        //new string[] { "fannhwu", "wafma", "gcje", "cvcia", "qwyh", "ugtbpa", "geufqg" },
        //new string[] { "kwtjib", "pqwai", "tdmjj", "kuxr", "euzl", "rxuk" },
        //new string[] { "ovi", "splc", "hflutgw", "hflutgw" },
        //new string[] { "gvel", "gelv", "aeiygth", "elvg", "twwr", "kivxrrj", "jkmqa" },
        //new string[] { "bas", "ylxbdgn", "yliv", "pytkhq", "haujsyf", "fggrnbc", "wsgree", "rfnppcx", "key", "gvdzgfy", "evdtrrz" },
        //new string[] { "oblab", "wpgm", "bpyy", "xuroy", "qhb", "adqko" },
        //new string[] { "hneb", "law", "uzms", "fhhk", "yjymdx", "wjla", "ixfh", "yblh" },
        //new string[] { "qlvsd", "bxsq", "hjaq", "fuwspzu", "hyshq", "idbabc", "rqcih", "ilixp", "wft", "rglf", "lmqm" },
        //new string[] { "qdskj", "two", "ckd", "qdt", "hzjvd", "woo", "fmmuw" },
        //new string[] { "kumc", "zywzq", "srafcbb", "ihfu", "kfvav" },
        //new string[] { "qlkkrq", "qlkkrq", "qlkkrq", "qsc" },
        //new string[] { "hob", "bpecik", "zqtrfz", "iqizeu", "plrer", "epm", "zqtrfz", "xrekeql", "xrekeql" },
        //new string[] { "warszd", "sxyyorh", "sxyyorh", "eztjf", "warszd", "kszp" },
        //new string[] { "hjbrax", "liumjue", "liumjue", "liumjue" },
        //new string[] { "rfnqd", "folmiu", "dlicln", "pdyk", "uqd", "rfnqd" },
        //new string[] { "mjdu", "lytfvya", "xomdujn", "leaqiyc", "lgemz", "lihfnhv", "zgeml", "koukz", "luqda" },
        //new string[] { "yqsz", "zedjmwn", "aep", "qwbhd", "yqsz" },
        //new string[] { "etg", "rmovps", "abizj", "yqr", "kib" },
        //new string[] { "yznxec", "sfqkd", "ofkzep", "njr", "hmeym", "nsh", "xdq" },
        //new string[] { "ryoyq", "heoo", "zuo", "udvfev", "ehoo", "axcnbpu", "oeho", "mfenmd", "shrebzy" },
        //new string[] { "uaeh", "jwllsjp", "frkhqsy", "uaeh" },
        //new string[] { "giofw", "hwceb", "euikqp", "ldmb", "kqpkxwv", "namazcg", "hqyyzgs", "cglsqux" },
        //new string[] { "qledbd", "qledbd", "kbwo", "wgfmgp" },
        //new string[] { "olbsca", "muxw", "nxs", "locsba" },
        //new string[] { "gbxxgj", "xlzm", "gws", "pkpwy", "ofkxb", "sykhdo", "nbhrv" },
        //new string[] { "najr", "bfk", "tbqkm", "hxabe", "nvr", "mdi", "dmuujr", "bfil", "nyripr", "zcydzy" },
        //new string[] { "kiczhcn", "dfgylw", "yzkwk", "nytijj", "pceu", "yukj", "ekaol", "xpb", "uep" },
        //new string[] { "acyyxn", "rwczsud", "acyyxn", "payiek", "inusyb", "rwczsud" },
        //new string[] { "mzssokx", "bshs", "bshs", "ocrvlug", "nzsgvch", "riejkrd", "jkj", "mpmdgsp", "kvixdfq", "msmmx" },
        //new string[] { "uaxy", "wpvhf", "uaaq", "ranp", "vfhwp", "iik", "kii", "nvh" },
        //new string[] { "shecxef", "nqpx", "jly", "dzm", "qvmpu", "kxg", "hdg" },
        //new string[] { "xembm", "yzevult", "ljrllc", "yrlskyk", "zas", "wstnz", "yrlskyk", "vasra" },
        //new string[] { "yoaxppi", "kzax", "hvxfezf", "mek", "teo", "cbtlrfa", "ncxac", "yee" },
        //new string[] { "dzfpbi", "cynov", "dje", "vxypba", "wcwww", "cwnu", "cqtp", "cnuw", "wwwcw", "rkzas" },
        //new string[] { "xzwdt", "jcwv", "anb", "xzwdt" },
        //new string[] { "fodgjem", "fmmrsfl", "eovsneo", "etzutda", "paw", "fmmrsfl", "jcqql" },
        //new string[] { "yfztt", "alcw", "nwdmd", "afgknu", "njxkj", "zykz", "cvv", "jbnl", "han", "iatmruu", "trqls" },
        //new string[] { "yas", "hpulrmf", "dzts", "sltg", "qsbw", "fjj", "rjymnnx", "dkkv" },
        //new string[] { "hwjtgd", "abmb", "cfw", "xoumxn", "xnoumx", "cxo", "xnxmuo", "alb" },
        //new string[] { "hnl", "zgdiip", "lrddhl", "fyw", "mporhtp", "waedf", "dltdfmc", "lyipoth", "ubmg", "hnl" },
        //new string[] { "wxard", "wxard", "cibp", "nzquvb", "muuslvw", "igvewfh", "mika", "wxard" },
        //new string[] { "cjqjhva", "rrhzy", "qpdc", "nqnyd", "enbdee", "ewrhp", "cqdp", "xekgjai" },
        //new string[] { "axtmxb", "axtmxb", "phl", "urdqaar", "urdqaar" },
        //new string[] { "umce", "jult", "bkart", "dgdvdwc", "kqzlzn", "nqkzlz", "umlxx", "cmue", "xvehqag", "wxifal" },
        //new string[] { "lwsuc", "ski", "ubo", "ksi", "sik", "qwcudv" },
        //new string[] { "husdv", "tssr", "gfp", "bfzbrp", "jtmk", "svvdpb", "uvshd", "zbnpdmj", "svpdvb" },
        //new string[] { "nnbvf", "xbb", "dobqk", "xwloqca", "uxvqti", "blcwxpu", "kubwu", "nognin", "goywn" },
        //new string[] { "xhe", "dhddftc", "ggltd", "dhddftc", "wspf" },
        //new string[] { "jodq", "cgvnk", "lpl", "wkwwlqd", "prfby", "bpyfr", "tbgyqm" },
        //new string[] { "bdebxj", "cuvow", "jdwdxw", "kuzh", "dvxmsyb", "dyvcxo", "psf", "kjnoe", "odfwgfa" },
        //new string[] { "xpfb", "knzgfsi", "thmsnbi", "ymjxn", "bevohy", "xpfb" },
        //new string[] { "hphcu", "fjodpdt", "mfsp", "jkvvp", "jvypar", "nlud", "lfv", "uftupcr", "nul", "dunl" },
        //new string[] { "olz", "ihyhw", "qntr", "lwcbohv", "qntr", "wzralwl" },
        //new string[] { "kfz", "pkjhidy", "msnmwz", "exox", "xexo", "uakipj", "mmznws", "zbbji", "ozispqb" },
        //new string[] { "gfi", "kwdhx", "qqo", "kdxwh", "fig" },
        //new string[] { "ehh", "rfozwr", "caoisw", "qntlk", "pkv", "zulc", "kpv", "hrqz" },
        //new string[] { "exmlrj", "aacc", "rzb", "qie", "rzb" },
        //new string[] { "mxyqe", "cuqz", "feyd", "meqyx", "gdvpu", "rqyjtvw", "dmoo", "vugdp", "emem" },
        //new string[] { "advj", "xmnad", "uvh", "ufnbi", "xmnad", "xmnad", "zzwjksx", "chbrjas", "hrbp", "ruvyg" },
        //new string[] { "nasrghk", "pmol", "ryko", "ofgakhd", "korf", "vpy", "nakrsgh" },
        //new string[] { "mylyqg", "aeizp", "rnk", "krlwchk", "aaqg" },
        //new string[] { "edxursp", "sosyv", "zesgnpx", "zlo", "sly", "alurdc", "ypmez", "qib", "aqtt", "lmxd" },
        //new string[] { "ihm", "hwzhd", "jhiw", "raocjk", "nlxce", "yzuzu", "nhudri", "tvygl", "tmclg", "mdkz" },
        //new string[] { "psubdis", "qrmxebg", "kdac", "xvl", "raxwfx", "vlx", "sxme" },
        //new string[] { "tci", "tphdy", "tggam", "vqqiyjz", "sgfvdri", "sxhztz", "fhsmxx", "yaj", "ncxcxq", "tic" },
        //new string[] { "xkljs", "cuhrm", "fdjqwd", "fuzyzh", "dzuzgjd", "lzpye", "lzpey" },
        //new string[] { "jriwl", "ypkcxd", "fxrg", "eit", "okzzzsc", "yaykarm", "qzuv", "jurgek", "dzfbbfl" },
        //new string[] { "workf", "rrw", "absfl", "gxluw", "qprdsz", "absfl", "qwqbmi", "amepvz", "oiqmy", "workf" },
        //new string[] { "dxyyb", "brnerbx", "lykd", "oqmz", "ursl", "zqom" },
        //new string[] { "cqtuzva", "aih", "uhaswd", "auhwds", "ktyvc", "hufogcg" },
        //new string[] { "jre", "fhlgrse", "svedc", "prfspaj", "ghm", "qcjzfc", "nsd" },
        //new string[] { "fow", "xyo", "vlvg", "sgg", "jgzvff", "rjxh", "eovre", "xtupnz" },
        //new string[] { "pekj", "pgiecc", "igxd", "zbiqoob", "ovv" },
        //new string[] { "xofxmz", "rdzdiq", "yruoqkh", "arfunx", "yruoqkh", "ucm", "bxov" },
        //new string[] { "ctogwj", "lpv", "ivtoxkf", "faj", "ctogwj", "xfzluad", "ctogwj", "vvw" },
        //new string[] { "rmc", "vjxj", "strgo", "tykifpp" },
        //new string[] { "ulivozu", "bczond", "ywnmt", "shakc", "yknr", "psr" },
        //new string[] { "bfx", "alwedh", "jfomlf", "pzj", "tely", "alwedh", "vccsoer", "rgwftcl", "vccsoer" },
        //new string[] { "frkwbv", "uudwt", "qsfg", "onuhiml", "jrd", "usu" },
        //new string[] { "bgdx", "deybefo", "gdj", "dgbx", "luu", "cbuwawd", "wqqtq", "dqmwy", "gin", "mhtfgy" },
        //new string[] { "ohjp", "ykemg", "nrs", "leayrh", "brtipx", "jhop", "phoj" },
        //new string[] { "utaep", "ywsy", "utaep", "ywsy" },
        //new string[] { "qow", "dxagjwb", "qbki", "bqik" },
        //new string[] { "larkpq", "bdgw", "mly", "vvwgv" },
        //new string[] { "juar", "zaerof", "qekpe", "hhgd", "eygru", "epekq", "dhgh" },
        //new string[] { "xpblz", "xksc", "lzue", "xksc", "yid", "nnve", "trlndn", "gjczngs", "cifqoaf" },
        //new string[] { "fpv", "ekz", "eknldf", "uqjgeu", "awwnwxu", "eknldf", "eknldf", "txhxv" },
        //new string[] { "mzvk", "wqtbda", "ovdbh", "vnes", "uiuuc", "uicuu", "bpwwtm", "aaat", "cygej", "nio", "gnl" },
        //new string[] { "rkdkzp", "bjaxqif", "xuwx", "bjaxqif", "hgtz", "slkqw", "rkdkzp", "ztp", "xfvgk", "ycvg" },
        //new string[] { "zpwr", "wvxzfcd", "opgcrfc", "ytxeboe", "rcqa", "ehrga", "lmgm" },
        //new string[] { "brsdnk", "nqgkjab", "nbjkaqg", "gho", "zqe" },
        //new string[] { "szbysu", "oqrtbp", "wjpuv", "oqrtbp", "oqrtbp", "gjmqq" },
        //new string[] { "uoyi", "ctscw", "uoyi", "ggn", "ija" },
        //new string[] { "fop", "lxa", "cgwpw", "lyvrxbe", "tit", "fop", "fop", "kfigqnu" },
        //new string[] { "ldqmk", "rxo", "ajhrbc", "ahrcjb", "xqdk", "kdxq" },
        //new string[] { "ith", "vdrl", "kvaxktm", "grkzmon", "ith", "ywbz", "kmnoiz" },
        //new string[] { "zdoo", "omjo", "fbz", "dveiipw", "fbz" },
        //new string[] { "ivj", "mcnu", "tkijlq", "xkq", "lrkyit", "cumn", "sfkrk", "numc", "ezxeeoi" },
        //new string[] { "lcwzdi", "sbsdgdy", "olvc", "olvc", "bimubzf", "bimubzf" },
        //new string[] { "cdjd", "umhwh", "djdc", "cddj", "oxheq", "veazlm" },
        //new string[] { "gxszn", "zsgxn", "azy", "yaz" },
        //new string[] { "byvmj", "mjybv", "jvxkuy", "akas", "uxyjvk" },
        //new string[] { "whmkttq", "whgzm", "gwmzh", "pkvtljw", "zgmhw", "jasudeq" },
        //new string[] { "yyjri", "fxsj", "xffmna", "vbal", "ftff", "rwq", "uszym", "bznil", "rfuctp", "ejndv", "wqr" },
        //new string[] { "gnwzjbw", "dezfvq", "gzkhzkl", "ivrdvxx", "wfah", "xvivrxd", "qzdvfe" },
        //new string[] { "xnfo", "zqzn", "iaod", "zlcclsd", "onxf", "lpskrfk", "nzqz", "kqzr", "kffpwak", "eky" },
        //new string[] { "muc", "tafbzp", "nra", "gvzc", "xiu", "gvzc" },
        //new string[] { "gfnbnyj", "nyjbfgn", "eoosw", "yjzf" },
        //new string[] { "qwwls", "sqwwl", "mxph", "swwql" },
        //new string[] { "twor", "uzjftq", "twro", "orwt" },
        //new string[] { "qomjuob", "bqaim", "zvfqww", "cvqzm", "wwipc", "zsywb", "bsqkp", "aoj", "fus" },
        //new string[] { "nlyd", "gtbgox", "tajlzgs", "bgtgxo", "pqt" },
        //new string[] { "pjtmgz", "ulblj", "ussh", "gngagba", "hhtexq", "bjbj", "obe", "xctciay", "osriw", "obe", "shxri" },
        //new string[] { "agc", "ejjdtak", "jgq", "moj", "agc", "iua", "syhxih", "znavmrc", "iih", "qubj" },
        //new string[] { "zxwzwhm", "lipkqhz", "bbv", "birxsj", "gzg", "iefrjh", "mprsfs", "ofpltbl", "gbo", "srpmsf", "hirm" },
        //new string[] { "rbpgqoe", "kymrf", "uzsut", "gkbtd", "xctpg", "qul", "hirtfl" },
        //new string[] { "wfvg", "pnqhuv", "jayjm", "ftqt", "mbrotl", "aydmoc", "lfwlxk", "vpvcsi", "svbn", "bnsv" },
        //new string[] { "jxjxza", "ysl", "kls", "vmt", "fvgunx", "hketl", "oshgie" },
        //new string[] { "dfeyxv", "akx", "qagwayp", "qrs", "lnulrle", "rqs", "gbvd", "bvdg" },
        //new string[] { "aac", "ndptml", "oke", "edwrg", "aac", "xechxz" },
        //new string[] { "mpx", "yrb", "oervzb", "ydvkw", "avlt", "oervzb", "bxdqbo", "hzwls" },
        //new string[] { "dsynfk", "dsynfk", "epexzjd", "epexzjd", "zofb" },
        //new string[] { "vhe", "zxfolqk", "lkh", "fxt", "flzkxqo", "lztwkmo", "khl" },
        //new string[] { "izlthi", "wtokkuz", "ousbpxp", "pvr", "uuxueq", "lvbeff", "mfk", "syjq", "fwgnfmg", "yytqesm", "gdd" },
        //new string[] { "kjcg", "slt", "khz", "atzw", "twpspdx", "kgyk", "wgq", "hjat", "ntf", "xvhxol", "msvdjs" },
        //new string[] { "ymm", "arrggw", "mmmbvrs", "ist", "arrggw", "nbvvc", "cwyacp" },
        //new string[] { "kuzglex", "iemp", "iemp", "jsko", "iemp", "oqs", "dheqypr" },
        //new string[] { "tzztq", "dsxqbow", "qgaeo", "kqn", "dsxqbow", "qqzpv" },
        //new string[] { "ysr", "fctpiyn", "psgb", "gatavv", "zsfxoxq", "nynfoh", "qaimoj", "zotjk", "nxug", "syr" },
        //new string[] { "xvm", "qvr", "hdxyhpf", "cbo", "xmv", "lfv", "wltyjlx" },
        //new string[] { "hjq", "pohc", "xgqit", "tducggu", "zdqmnc", "xqgit", "tqxgi", "srfyzu", "vdikqx" },
        //new string[] { "msiqte", "ewvp", "bzrv", "cmuy", "gse", "qqayvb", "bzrv", "qehy" },
        //new string[] { "watdvu", "ametrc", "etlduhh", "vcc", "luehdth", "udavtw" },
        //new string[] { "jktj", "mkq", "jktj", "mkq" },
        //new string[] { "uekth", "ufjkmdi", "qzhge", "wzwcwk", "nvrodcc", "vrcdocn", "bhcvd" },
        //new string[] { "xumywk", "zwofh", "kuxmyw", "acgzsjj", "hfowz", "njnz", "bnklyi" },
        //new string[] { "hmm", "fexu", "fexu", "hmm" },
        //new string[] { "zeuoarc", "yoa", "ggff", "jazzd", "mjein", "yhj", "qwo", "qwo" },
        //new string[] { "rolkwf", "fcyat", "lwm", "wqqm", "juwkt", "wqqm", "udj", "tex", "xgps", "nyy", "pdbkkhb" },
        //new string[] { "gld", "ksl", "gld", "bnsuhqc", "gld", "rwmybj" },
        //new string[] { "tvyxk", "xgmk", "cri", "pef", "epf", "unsl", "yktxv" },
        //new string[] { "muiql", "ejq", "taetjkf", "ejq", "xzmo", "wmv", "qbtmrh", "hkfbch", "taetjkf", "sut" },
        //new string[] { "pqg", "icvv", "gpq", "tufd", "iixd", "duft" },
        //new string[] { "zekx", "ybbb", "gzml", "vrbwcl", "opfb", "fkrv", "tto", "cbipr" },
        //new string[] { "moh", "stkkf", "ynrtdf", "jlgb", "kstfk", "ksktf" },
        //new string[] { "nvysvf", "mdtdoq", "bqqvr", "bqqvr" },
        //new string[] { "dqyz", "mzoqtp", "gzhdgd", "symsq", "iwh", "bpwox" },
        //new string[] { "pkqi", "jgzsrah", "yfjxx", "kdp", "xjaf", "lbj", "gkpixnj", "tyvzzso", "qmjbo", "skg", "nlchzbk" },
        //new string[] { "culxfx", "jarwu", "eiwriu", "vwvg", "gvwv", "sgnasz" },
        //new string[] { "kyfsn", "dwc", "sbnoe", "xwpgjh", "nbmvec", "dwc", "qjdh", "mpw", "gefimue", "fvqjwt", "kkor" },
        //new string[] { "hcdcgxs", "fof", "flc", "hfpjy", "lii", "fihcao", "pxg", "xywei", "jwsq", "yxr" },
        //new string[] { "oxrcv", "pda", "oxrcv", "gdvojsz", "kmlga", "mixlmp", "hdcabsn", "qvoa", "fwt" },
        //new string[] { "poe", "joylchz", "humrjy", "cyxbqfm", "lyk", "ybrfmp", "qmtpqyk", "vtpr", "lyk", "vtpr" },
        //new string[] { "ffswqs", "yxbuj", "tfzkmc", "yxbuj", "giog", "ckubbfy", "rtigw", "rtigw", "rpitxd" },
        //new string[] { "kcvrn", "eejyftw", "ejytfew", "rnckv" },
        //new string[] { "lvk", "lkv", "cooumh", "vlk" },
        //new string[] { "loypv", "ukowl", "loypv", "nyoyfl", "vehnm", "uff" },
        //new string[] { "tst", "sei", "zovy", "itdwibj", "mcbtst", "wcf", "rzp", "xvbtax", "ffzp", "xieenuy", "aegkj" },
        //new string[] { "zkhi", "hvsbgza", "xbwtdns", "wypfngy", "lvabd", "pybhcd", "crczm", "buikdpo", "vqgon", "pynfwyg", "phbcdy" },
        //new string[] { "ihy", "irxrj", "entmc", "yxfhbta", "xsdv", "xsdv" },
        //new string[] { "ezrcv", "kfgm", "pjneez", "puccy", "gzpxdlf", "gkfm", "yucpc", "mli", "xezfug" },
        //new string[] { "umjppkq", "idkiri", "wmnbhi", "unl", "nteyw", "wmnbhi", "zyv", "idkiri", "shhcrau" },
        //new string[] { "dzj", "zveqwae", "ljnikvb", "baavr", "dhsohp", "zveqwae", "goq", "zveqwae" },
        //new string[] { "xhc", "xch", "bmttdr", "snd", "jakd" },
        //new string[] { "jmgnvda", "bdpzfw", "dfwpzb", "pimpv", "blqtbyo", "lzdzo", "bgrlfy", "anmjvdg" },
        //new string[] { "lwvu", "ksg", "gqbtibd", "ksg", "lwvu", "ohfzlt", "foajo", "apyrcwj", "uaro" },
        //new string[] { "vel", "qksrwp", "zei", "ipnvd", "hdua", "rkspqw", "bujf" },
        //new string[] { "iozkiu", "upa", "knmcug", "zidypn", "yswb", "zswkvx", "naqsu" },
        //new string[] { "tjktoe", "dqpt", "pbqi", "dqpt" },
        //new string[] { "lcl", "tui", "uoizm", "xrdpmwi", "fbsuuqq", "tgeac", "hpajm", "tegac", "nczlic" },
        //new string[] { "ntmm", "mskzb", "arem", "ntmm", "jayzfe", "wyurgsh", "eqwcqt", "edhska", "asxhjv", "jayzfe" },
        //new string[] { "jyq", "juifidx", "fokzxh", "cgo", "xofhzk", "nhro", "xyccuq", "ioa", "nwk", "nqaxpfw" },
        //new string[] { "cvag", "bpk", "cuo", "ocu", "buehhq", "tartafi", "ifs", "qwh", "cveurg" },
        //new string[] { "bwut", "xpfni", "qzg", "cmp", "cid", "jftawv", "twiszmo" },
        //new string[] { "zgxc", "sui", "kypkd", "vpam", "ymxicrw", "jcfbutd", "fgx", "jcfbutd" },
        //new string[] { "tkxn", "rjqzljh", "tkxn", "mdwcho" },
        //new string[] { "qbv", "zneocv", "zneocv", "zneocv" },
        //new string[] { "tywf", "soncr", "lyepx", "qzj", "xdsr", "pdqv", "swt" },
        //new string[] { "ulu", "rdk", "iomqu", "dgouoba", "icax" },
        //new string[] { "ddsc", "oxilqpd", "ddsc", "atbekg", "ouzmxf", "oxilqpd", "kwtzz", "yhmyd", "otvi" },
        //new string[] { "vtj", "llnfrpc", "vfighju", "urosrsz", "vurtse", "llnfrpc", "qeuo", "vfighju", "nnn", "smsnp", "tfom" },
        //new string[] { "updfjmz", "ngtgi", "zaitq", "rqqhcyn", "ladzx", "zaitq", "fbaphyz", "hipe" },
        //new string[] { "rii", "fpos", "atl", "tal", "qhubqdv", "lat" },
        //new string[] { "whxzwdj", "yznkngr", "eefbmub", "wnxitd", "tnwxid", "zja", "ziewilm", "xylwn", "ihhsha", "lrptuyf" },
        //new string[] { "fhmzaxv", "mdn", "udl", "gyv", "pqw", "qlrz", "flm", "rqtji" },
        //new string[] { "bgn", "clnm", "cnml", "qyh", "hhf", "qqnur", "sgvigvm" },
        //new string[] { "qjtbysc", "ycbqjts", "gbgvlz", "vgzlgb", "dgxks", "qbvp", "grji", "dcc" },
        //new string[] { "wmduuq", "qayymzo", "zvh", "ylbipw", "sin", "ybwpli", "ilypwb" },
        //new string[] { "qsvzktt", "qsvzktt", "dasmg", "knh", "gcgep", "qai" },
        //new string[] { "jxukj", "qlgr", "cjssj", "aavqv" },
        //new string[] { "xpxa", "glsdfxq", "ngxwon", "ytuue", "pizqu" },
        //new string[] { "fxl", "vegoed", "tct", "luwm", "ulwm", "eeovdg" },
        //new string[] { "ntmpe", "auasx", "vkwgi", "cryuiix", "dmiufo", "fcb", "ldl", "jauncf", "gyouym", "asjcryc" },
        //new string[] { "lgwdcs", "eoxm", "hcrpnuf", "pcfnhru", "vlye", "fpurcnh", "uquukv", "vjc" },
        //new string[] { "lfns", "riwpdh", "phwxvew", "hhu", "jfptvv", "ofxd", "hkotgfq" },
        //new string[] { "qvuwnq", "wnpvs", "xdivrfz", "yaenqr", "fipwgl" },
        //new string[] { "vhcexfd", "bishqsc", "gsbruxm", "yzccyot", "yjloa", "aptg", "vbr", "gsbruxm", "ihqhyz", "yzccyot" },
        //new string[] { "knfst", "zhihi", "swhhq", "zhihi" },
        //new string[] { "qfto", "abhjx", "abhjx", "bpnijn", "ogmqxn", "rclqag", "dmeb", "rdogx", "emfriui", "hyvp", "ogmqxn" },
        //new string[] { "ivaemm", "wlsc", "dvjv", "aivemm", "xvf", "shfonv" },
        //new string[] { "vowhosr", "vptlu", "ucrut", "rdynh", "ttqvhg", "rdynh", "abtja", "pnvdy", "puxfmf", "dyhd" },
        //new string[] { "uvrenol", "ycuhvy", "ygm", "fjsxiwo", "oftstid", "ygm" },
        //new string[] { "fix", "qrqeg", "dfgvlun", "fix", "iraxgtt", "lhgqdo", "eqkgshd", "jwmrm", "qrsbzba" },
        //new string[] { "mxdj", "icjqzqw", "fvew", "gtvlhm", "mxdj" },
        //new string[] { "cyjtkm", "crb", "pmg", "jwo", "iluc", "brc", "ttnd" },
        //new string[] { "dasmgp", "ool", "ool", "opc" },
        //new string[] { "ubi", "pmz", "mtkh", "ibu", "hlx", "ipcvjki", "sydw", "zpm", "eewfdeu", "oga" },
        //new string[] { "avex", "yjaoghv", "yjaoghv", "lwwx" },
        //new string[] { "kwkdst", "iuokd", "nmpw", "onayet", "zlavwnd", "wwvbr", "jtrkyku", "wfxx", "dumydgh", "gnd", "zgi" },
        //new string[] { "ahyjnc", "rjakp", "bhabq", "tsmfi", "ahyjnc", "tsmfi", "yitqgi", "uwnywil", "shnkbn" },
        //new string[] { "krr", "sbbfjtm", "yvunas", "hwppsjf", "ntuuzw", "ngyvdmt", "ynk", "nfq", "mfrb", "pyw", "hngr" },
        //new string[] { "eeecesf", "phoo", "ijmx", "sjp", "kgmtg", "sjp", "wyz" },
        //new string[] { "qwixmou", "oximqwu", "ixu", "lsmf" },
        //new string[] { "dyrzq", "lbstdjv", "ldvowml", "qjf", "fqj", "zpabc", "dwmvoll", "jnq" },
        //new string[] { "pdtlu", "hgcfvz", "mnwjyq", "ymi", "cvcp", "kmx", "mkx", "ooffp", "uiwg", "opoff", "uevqt" },
        //new string[] { "hflomt", "fhlmto", "gutdbyp", "xyi", "zpggxc", "wqe" },
        //new string[] { "jpsr", "wwex", "yjgdj", "fqah", "wrmmw", "nyrnw", "hcomcgv", "teajmu", "emw", "zrraid" },
        //new string[] { "tvgsca", "bzgzkga", "ypsxsk", "dqz", "exmu", "tvgsca", "dqz", "qnd" },
        //new string[] { "arzn", "hojpi", "bznw", "ejuupe", "bznw", "hojpi" },
        //new string[] { "rids", "dule", "qaefaon", "sspit", "mtzgdls", "cfujw", "xldhimi", "igdoy", "dule" },
        //new string[] { "nefsys", "plea", "obksngc", "zxqee", "avsi", "obksngc", "vnsxdrl", "gspadob", "avsi", "owmzpeh", "tcj" },
        //new string[] { "oweq", "fkr", "krf", "rfk", "ztwjdry", "shzcmew", "jhna" },
        //new string[] { "hdjizhg", "dfclic", "usds", "luz", "mcwyj", "luz", "qvomls", "mren", "otax" },
        //new string[] { "pmzzfj", "pmzzfj", "wfxyq", "mqv", "hyp", "lhf" },
        //new string[] { "dxeaw", "ckkey", "ccvawo", "keaf", "izlh", "oacvcw", "lgcpgeh", "kdiky" },
        //new string[] { "xkwe", "xekw", "kwex", "tzfyx" },
        //new string[] { "dmmyt", "mtdnqw", "pdw", "vdav", "ofrtsk" },
        //new string[] { "klz", "zlk", "snxnihg", "snhigxn", "zkynpd" },
        //new string[] { "ijzce", "xobf", "uojezxi", "xiuojez" },
        //new string[] { "ztepv", "zvpet", "nije", "aditjlg", "natkkk", "dtitg", "jprgia" },
        //new string[] { "fesuh", "wadrhc", "bayf", "kktfaf", "nxvhq", "smbdaop", "gqx", "ioez", "fkjufb", "abyf" },
        //new string[] { "hej", "sta", "pztkcd", "pesabzz", "szp", "iada", "iada", "cdae", "hej", "sqst", "luf" },
        //new string[] { "xlnuhn", "oljaf", "fljao", "ascxez", "fojal" },
        //new string[] { "dprclb", "fzn", "wgauz", "rxewtp", "cjrlgz", "zfn" },
        //new string[] { "fidwoa", "mvoqy", "afian", "ntzokap", "mkplgy", "jfukgjv", "cyfsz" },
        //new string[] { "hbvqnnt", "giinuzq", "uezugy", "qooxjc", "zsxr", "rnihg", "ipbels" },
        //new string[] { "qroi", "wtltjq", "suj", "tqit", "bxtc", "jidzhpe", "nizp", "wtltjq", "nadcdm", "wwyhjrg" },
        //new string[] { "qtr", "fkbl", "bpptu", "baen", "awjpwsg", "vvqbxz", "animt", "uqbk", "zvbxvq" },
        //new string[] { "nznq", "fdiul", "jbv", "umyrf", "yufrm", "hrl", "duilf" },
        //new string[] { "bkvlfuw", "onkqzeo", "iwrg", "rifqzhj", "mgroul", "rnor", "qqqc", "sbfi", "hny", "zosfp", "kopxb" },
        //new string[] { "nvifbx", "jbowbj", "fnyskt", "jbowbj", "xvun", "xvun" },
        //new string[] { "piyl", "haajm", "stwzpp", "xvjg", "amjah" },
        //new string[] { "gye", "efwwwiv", "kyv", "zmtcgmi", "ifwvwew" },
        //new string[] { "dflx", "gdtb", "jyoj", "jyoj", "dflx", "aqhycgi", "xffnn" },
        //new string[] { "inc", "mpys", "mzqmcwx", "vryz", "ibqrzc", "pmsy", "fat", "rojpxwy", "rcbqzi", "gjef" } };
        //part 2            
        //var part2Count = 0;
//            for( var i =0;i<input.Length;i++)
//            {
//                if (!wordCheck(input[i]))
//                    part2Count++;
//            }
//            Console.WriteLine("The count is {0}", part2Count);
//            Console.ReadKey();
//        
        //part 1
            //            var count = 0;
            //            for (var i = 0;i<input.Length;i++)
            //            {
            //                if (!checkLine(input[i]))
            //                    count++;
            //            }
            //            Console.WriteLine("The count is {0}", count);
            //            Console.ReadKey();
            //        }
            //        internal static bool checkLine(string[] input)
            //        {
            //            for(var i = 0;i<input.Length;i++)
            //            {
            //                for(var j=i+1;j<input.Length;j++)
            //                {
            //                    if(input[i] == input[j])
            //                    {
            //                        return true;
            //                    }
            //                }
            //            }
            //            return false;
            //        }
        //internal static bool wordCheck(string[] input)
        //{
        //    for(var i =0;i<input.Length;i++)
        //    {
        //        char[] start = input[i].ToCharArray();
        //        Array.Sort(start);
        //        for (var j = i+1;j<input.Length;j++)
        //        {
                    
        //            char[] next = input[j].ToCharArray();
        //            Array.Sort(next);
        //            var letterCount = 0;
        //            if (start.Length == next.Length)
        //            {
                        
        //                for (var k = 0; k < start.Length; k++)
        //                {
                            
        //                    for (var l = k; l <= k; l++)
        //                    {
        //                        if(start[k] == next[l])
        //                        {
        //                            letterCount++;
        //                        }
                                
        //                    }
                            
        //                }
        //                if (letterCount == start.Length)
        //                    return true;
        //            }
                    
        //        }
        //    }
            
        //    return false;
        // }
        //}
    }
}
